version: '3.9'
networks:
 basic:
services:
  backend:
    build: 
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    container_name: backend
    image: sms_messaging/backend:latest
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./:/sms_messaging/:rw
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:rw
    environment:
      PYTHONUNBUFFERED: 1
    command:
      - /bin/bash
      - -c
      - |
        bash backend_start.sh
    networks:
      - basic
  frontend:
    build: 
      context: ./
      dockerfile: ./docker/frontend/Dockerfile
    container_name: frontend
    image: sms_messaging/frontend:latest
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./:/sms_messaging/:rw
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:rw
    environment:
      PYTHONUNBUFFERED: 1
    command:
      - /bin/bash
      - -c
      - |
        bash frontend_start.sh
    networks:
      - basic






